# file: .github/workflows/hello-world.yml
name: workflow
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 20
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle Init
      run: gradle init

    - name: Gradle Wrapper
      run: gradle wrapper

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Execute Gradle tasks --all
      run: ./gradlew build  

    - name: Execute Gradle checkstyleMain
      run: ./gradlew checkstyleMain
    #- run: gradle test
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: app/src/main/java
        with:
        coverageCommand: make report
        coverageLocations: ${{github.workspace}}app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco